In [1]:
import numpy as np

In [4]:
array = np.array([[1,2,3],
                  [2,3,4]])

In [5]:
print(array)

[[1 2 3]
 [2 3 4]]


In [6]:
array.ndim

2

In [7]:
array.shape

(2, 3)

In [8]:
array.size

6

In [9]:
a = np.array([2,3,4],dtype = np.int64)
print(a)
print(a.dtype)

[2 3 4]
int64


In [2]:
a1 = np.eye(4)
print(a1)
print(a1.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [4]:
a2 = np.identity(4)
print(a2)
print(a2.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [7]:
a3 = np.empty((4,4))
print(a3)
print(a3.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [10]:
b = np.array([2,3,4],dtype = np.float64)
print(a)
print(b.dtype)

[2 3 4]
float64


In [11]:
b1 = b.astype(int)
print(b1.dtype)

int64


In [12]:
c = np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
c1 = np.random.normal(size = (4,4))
print(c1)
print(c1.shape)
print(c1.dtype)

[[ 0.18531205 -0.19420093  0.80075376 -0.62439395]
 [ 0.58533793  0.40244541  0.08096678 -1.54549482]
 [-1.1533894   0.98238939 -0.88338634 -0.18434848]
 [-1.09858737  1.47878096  1.21973013 -1.44991999]]
(4, 4)
float64


In [19]:
d = np.ones((3,4), dtype = np.int64)
print(d)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [20]:
e = np.empty((3,4))
print(e)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
f = np.arange(10, 20, 2)
print(f)

[10 12 14 16 18]


In [22]:
g = np.arange(12).reshape((3,4))
print(g)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
h = np.linspace(1,10,25)
print(h)

[ 1.     1.375  1.75   2.125  2.5    2.875  3.25   3.625  4.     4.375
  4.75   5.125  5.5    5.875  6.25   6.625  7.     7.375  7.75   8.125
  8.5    8.875  9.25   9.625 10.   ]


In [29]:
i = np.linspace(1,10,24).reshape((8,3))
print(i)

[[ 1.          1.39130435  1.7826087 ]
 [ 2.17391304  2.56521739  2.95652174]
 [ 3.34782609  3.73913043  4.13043478]
 [ 4.52173913  4.91304348  5.30434783]
 [ 5.69565217  6.08695652  6.47826087]
 [ 6.86956522  7.26086957  7.65217391]
 [ 8.04347826  8.43478261  8.82608696]
 [ 9.2173913   9.60869565 10.        ]]


## Basic Calculation

In [30]:
m = np.array([10, 20, 30, 40])
n = np.arange(4)
print(m)
print(n)

[10 20 30 40]
[0 1 2 3]


In [31]:
a = m - n
print(a)

[10 19 28 37]


In [32]:
b = m + n
print(b)

[10 21 32 43]


In [33]:
c = n ** 2
print(c)

[0 1 4 9]


In [35]:
d = np.sin(m) * 10
print(d)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [36]:
print(n < 3)

[ True  True  True False]


In [37]:
print(n == 3)

[False False False  True]


In [39]:
m = np.array([[1,1],
              [0,1]])
n = np.arange(4).reshape(2,2)
print(m)
print(n)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [40]:
a = m * n
print(a)

[[0 1]
 [0 3]]


In [41]:
b = np.dot(m, n)
print(b)

[[2 4]
 [2 3]]


In [42]:
c = m.dot(n)
print(c)

[[2 4]
 [2 3]]


In [43]:
m = np.random.random((2,4))
print(m)

[[0.52126413 0.00892609 0.72953078 0.13517024]
 [0.49627867 0.33534562 0.01419736 0.34806981]]


In [47]:
a = np.sum(m)
b = np.max(m, axis = 1) #row
c = np.min(m, axis = 0) #column
print(a,b,c)

2.5887827145792874 [0.72953078 0.49627867] [0.49627867 0.00892609 0.01419736 0.13517024]


In [48]:
m = np.arange(2,14).reshape((3,4))
print(m)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [49]:
a = np.argmin(m)
print(a)

0


In [50]:
b = np.argmax(m)
print(b)

11


In [51]:
c = np.mean(m)
print(c)

7.5


In [52]:
d = np.average(m)
print(d)

7.5


In [53]:
e = np.median(m)
print(e)

7.5


In [54]:
f = np.cumsum(m) #runing total
print(f)

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [55]:
g = np.diff(m)  #Calculate the diffrence between number and previse number
print(g)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [56]:
h = np.nonzero(m) #return the index of non-zero element
print(h)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [57]:
i = np.sort(m)
print(i)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [60]:
j = np.transpose(m)  #pivot table
print(m)
print(j)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]


In [61]:
k = np.clip(m, 5, 9)
print(k)

[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]


In [63]:
m = np.arange(3,15)
print(m)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [64]:
a = m[3]
print(a)

6


In [65]:
n = np.arange(3,15).reshape(3,4)
print(n)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [69]:
b = n[2] # 2 is index of row
print(b)

[11 12 13 14]


In [70]:
c = n[1][1]
print(c)

8


In [71]:
d = n[1,1]
print(d)

8


In [72]:
for row in n:   # print each row number
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [74]:
print(n.T)  # print each column number, you need pivot table first

[[ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]
 [ 6 10 14]]


In [75]:
for column in n.T:   
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [78]:
e = n.flatten()
print(e)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [80]:
for item in n.flat:
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14


## combine array

In [3]:
m = np.array([1,1,1])
n = np.array([2,2,2])
print(m,n)

[1 1 1] [2 2 2]


In [5]:
c = np.vstack((m,n))   #vertical stack
print(c)

[[1 1 1]
 [2 2 2]]


In [7]:
print(m.shape)
print(n.shape)
print(c.shape)

(3,)
(3,)
(2, 3)


In [8]:
e = np.hstack((m,n))  # horizontal stack
print(e)
print(e.shape)

[1 1 1 2 2 2]
(6,)


In [11]:
f = m[np.newaxis, :]
print(f)

[[1 1 1]]


In [12]:
g = m[: , np.newaxis]
print(g)

[[1]
 [1]
 [1]]


In [14]:
h = np.concatenate((m,n,m))
print(h)

[1 1 1 2 2 2 1 1 1]


In [19]:
i = np.concatenate((m,n,m,n), axis = 0)   #When working with 1D arrays, you can only concatenate them along axis 0
print(i) 

[1 1 1 2 2 2 1 1 1 2 2 2]


## split array

In [20]:
m = np.arange(12).reshape((3,4))
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
a = np.split(m, 2, axis = 1)  #split by column
print(a)

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [24]:
b = np.split(m, 3, axis = 0)  #split by row
print(b)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [25]:
c = np.array_split(m, 3, axis = 1)
print(c)

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [27]:
d = np.vsplit(m, 3)
e = np.hsplit(m, 4)
print(d)
print(e)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


## Copy & deep copy

In [28]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [35]:
b = a
c = a
d = b

In [34]:
b is a

True

In [36]:
a[0] = 5
print(a)

[5, array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [37]:
c is a

True

In [38]:
d is a

True

In [39]:
b = a.copy()   #deep copy
print(b) 

[5, array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [40]:
a is b

False

## Broadcast

In [16]:
weathers = np.array([[20,21,22,18,19,21,22],[18,21,23,19,18,21,13],
                      [18,19,22,21,21,17,16],[15,18,20,19,21,17,18]])
print(weathers.mean(0))
meaned = weathers - weathers.mean(0)
print(meaned)
print(meaned.mean(0))

[17.75 19.75 21.75 19.25 19.75 19.   17.25]
[[ 2.25  1.25  0.25 -1.25 -0.75  2.    4.75]
 [ 0.25  1.25  1.25 -0.25 -1.75  2.   -4.25]
 [ 0.25 -0.75  0.25  1.75  1.25 -2.   -1.25]
 [-2.75 -1.75 -1.75 -0.25  1.25 -2.    0.75]]
[0. 0. 0. 0. 0. 0. 0.]


## Transpose

In [20]:
ar1=np.array([[1,1,1,1,1],[2,2,2,2,2],
              [3,3,3,3,3],[4,4,4,4,4],
              [5,5,5,5,5]])
ar1_trans = ar1.transpose()
print(ar1)
print(ar1_trans)

[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [21]:
ar2_trans = ar1.T
print(ar2_trans)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


## Ufunc

In [23]:
au1 = np.arange(10)
print(au1)
au1_sqrt = np.sqrt(au1)
print(au1_sqrt)

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


## reduce

In [26]:
a11 = np.arange(0, 101)   # calculate the total number form 1 to 100
a11_total_sum = np.add.reduce(a11)
print(a11)
print(a11_total_sum)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
5050
